title:            Danielle Sucher
description:      
url:              # Site url.
signoff:          Danielle
disqus_shortname: DanielleSucher
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /
  - name:         Projects
    url:          /projects
  - name:         Blog
    url:          /blog
  - name:         Tags
    url:          /tags
  - name:         Email
    url:          mailto:dsucher@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/DanielleSucher
    external:     true
  - name:         Twitter
    url:          http://twitter.com/DanielleSucher
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
paginate: 5
paginate_path: "blog/page:num"
redcarpet:
  extensions:
    - smart
    - no_intra_emphasis
